language: node_js
cache:
  directories:
    - ~/.cache/Cypress
    - ~/.cache/yarn
script:
  - yarn run prettier
  - yarn run lint
  - yarn run test
  - yarn run build
  - yarn run serveAndRunUiTests
